version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22182:2182"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22183:2183"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "29091:29091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9091,PLAINTEXT_HOST://localhost:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-2
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-2:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-3
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-1:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-1
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SERVER_PORT=8081
      - KAFKA_CLUSTERS_0_NAME=INPUT
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9091
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

  kafka-ui-2:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-2
    ports:
      - "8082:8082"
    restart: always
    environment:
      - SERVER_PORT=8082
      - KAFKA_CLUSTERS_0_NAME=OUTPUT-1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-2:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2182

  kafka-ui-3:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-3
    ports:
      - "8083:8083"
    restart: always
    environment:
      - SERVER_PORT=8083
      - KAFKA_CLUSTERS_0_NAME=OUTPUT-2
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-3:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2183